### ISSUE TITLE
Set up and configure Jekyll

### ISSUE THREAD

**Issue by satukoskinen** [Hive-Hexagon/hive-hexagon.github.io#2]
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyl
https://jekyllrb.com/docs/

**Comment by satukoskinen** [comment]
I have now generated the basic Jekyll template without any modifications.

**Comment by juliuskoskela** [comment]
Please send the PR already!
